name: yumyum_crm_flutter
description: "YumYum CRM Flutter Application - 맛있는 배달 서비스 관리자 페이지"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # 상태 관리
  flutter_riverpod: ^2.6.1
  riverpod: ^2.6.1
  
  # 네비게이션 & URL 관리
  go_router: ^14.8.1
  url_strategy: ^0.3.0
  
  # 네트워크
  dio: ^5.7.0
  http: ^1.2.2
  
  # 로컬 저장소 (웹 최적화)
  shared_preferences: ^2.3.2
  shared_preferences_web: ^2.4.2
  
  # JSON 처리
  json_annotation: ^4.9.0
  
  # UI 구성 요소
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296
  
  # 차트 (웹 성능 최적화)
  fl_chart: ^0.69.2
  
  # 이미지 처리 (웹 전용)
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.5
  
  # 파일 처리 (웹 최적화)
  file_picker: ^8.3.7
  
  # 날짜/시간
  intl: ^0.19.0
  
  # 로딩/프로그레스 (웹 최적화)
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.1
  
  # 폼 유효성 검사
  form_field_validator: ^1.1.0
  
  # 반응형 디자인 (웹 최적화)
  responsive_framework: ^1.5.1
  flutter_screenutil: ^5.9.3
  
  # 테이블 (웹 성능 최적화)
  data_table_2: ^2.5.15
  
  # 웹 전용 최적화
  web: ^1.1.0
  js: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  
  # 코드 생성
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
